/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.2.1/userguide/java_library_plugin.html
 */

plugins {
  // Apply the java-library plugin to add support for Java Library
  `java-library`
}

repositories {
  // Use jcenter for resolving your dependencies.
  // You can declare any Maven/Ivy/file repository here.
  mavenCentral()
  jcenter()
}

dependencies {
  // This dependency is exported to consumers, that is to say found on their compile classpath.
  //api("org.apache.commons:commons-math3:3.6.1")

  // This dependency is used internally, and not exposed to consumers on their own compile classpath.
  implementation("com.google.code.findbugs:jsr305:3.0.2")
  implementation("javax.inject:javax.inject:1")
  implementation("com.google.errorprone:error_prone_annotations:2.3.3")

  //Test stuff
  testImplementation("com.google.guava:guava:27.0.1-jre")

  testImplementation("junit:junit:4.12")
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.4.0")
  testImplementation("org.junit.jupiter:junit-jupiter-params:5.4.0")
  testImplementation("org.junit.vintage:junit-vintage-engine:5.4.0")
  testImplementation("org.junit.jupiter:junit-jupiter-engine:5.4.0")
  testImplementation("org.assertj:assertj-core:3.12.2")

  testImplementation("io.strikt:strikt-core:0.19.2")
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit:1.3.21")

  //Kotlin specific stuff
  testImplementation("org.jetbrains.kotlin:kotlin-stdlib:1.3.21")
}
