language: java

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - file target/travis/settings.xml
  - echo target/travis/settings.xml

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jdk:
- oraclejdk8

notifications:
  email: false

install:
  - mvn dependency:resolve
  - mvn validate -N

script:
  - git describe
  - echo "Building branch <${TRAVIS_BRANCH}>"
  - "[ ${TRAVIS_BRANCH} = 'develop' ] && mvn clean deploy --settings target/travis/settings.xml -B -U --show-version || mvn clean verify --settings target/travis/settings.xml -B -U --show-version"

env:
  global:
    secure: qNPEvunZkvhHyj9FOji1a++aMYH5OnzXOCFINOIx9bPumvDwtfMbDwywXq0Wqn2KM5Mn3G99xvQR0FR2Mad7QjMd0yJiDBhcCQfIFstZLxjjTeALZRgnYXdRkAOaq4z8rt9GGDYszUepbjtOLotn9ER0qS7hyhXZ3wQ/PVrjZHiSZnn/cwIzveZg3MwQTbbhTL2ayK/x4ED0Bo+jyv5+QDLwRJaxkQu9b3boXW7woOvkhSDmKqnUjY3xPnayDw7uXd1X8CfeYRZ8DcWJHmOkXdyqD9oiGeqO73K3w1ERDN2FMPdL8ch7vAGfyqZUe/vpD0wgf4u2q35FyTJvCBaZ+oHJzM51KMUp/Fmwo84s9IMH3SyxlV95k/aLP5bK4kw9zkdXT2q7v/imPpCl1PMxt3YuJ2+Qke9JjnDxWyrPdXlXkwyqWUCfh0ZVuXrY3huc/IBM4R8tE3RISBfZPngDz5plNdnyDqFaujx7k8nnmEcrlZI6V4DP5KTJqklBAvdYC+0vMiwkNSeeq7AnRuNGvg/JzLY0KysBWdtvUjJCnrYlhdvpFjuWfAZ47TT4FuYe/fMq3B0yWX18vX2k/Hgp4A1HKp7VL1BuG5YOtSa9RL1fRDbaEqOMhItOu5ZwTex/1J2L36l2n907uQ2pte4mGNzy96+7PXRaMIHF1p0MoJA=
    secure: lwds6D1TDUWpiar4Mjczw8ZLbunNkhilj5/fDT2VqTp9ovICDy9XNCKMIYtc+1HAYs72ULRdRZc5r7VY5i8Z4ITSTHLQ5hxHhEhVTB6Tnha0iF9N7U7hwD3+ZfGzP97Y67NmCS24H5Lyy6O1s+2J+7BOLL95XLTTlMOD5dNcfOW2iiomDAAAOrxwpgAghaZXnOUOSNo3lQB9dx2bayEDy6gm1tNhdhFRZasvPY0BhY/uapeQh8vW7EX3Ne9zkhhuaUi9AjfH9r1ogYUSySU4UnZEPs1QbF5TScwyAdXS9Z5lSMciSLPqoHB4wza0zlhGK7mz0OVCkD9iujJO8FjQxxyXIfezrPUCleLwpEXTeyb4eo32gE4T3sgvncgrpBPNlyH4jH6kr/rFH9rd9s5b1geBj3bC4V9Q9NrOA1WIFitSAXNcrip50mpKc+81DIZnFrGurhXjV8vkFeH996xuOu1MLDa3z3YYNRARPvuW5keG1LtCsaG1FEwYXPEbNm6nmybMRlHqluQ9Q0sW+fC1AdqwP+ESk76ah1OGpolJXVi+OxiwYno9GebYPG/ar1aNTd0GuJVjXdKl4aFO9rwfnJQAqDXDynjpKQlfpwPgv54SHgASSuXps7ptE9gybsSmn6CtCAtZHxqzOYC0oNc1WCQSvBHasfxxmV7WIy7MZWU=


before_cache:
  - rm -rf $HOME/.m2/repositor/com/cedarsoft/monorepo
cache:
  directories:
  - $HOME/.m2
