package com.cedarsoft.commons.kotlin.serializers

import com.cedarsoft.common.collections.DoubleArray2
import com.cedarsoft.commons.serialization.roundTrip
import org.junit.jupiter.api.Test

class DoubleArray2SerializerTest {
  @Test
  fun testIt() {
    val value = DoubleArray2(10, 8) {
      it * 3.0
    }

    roundTrip(value, DoubleArray2Serializer) {
      """
        "AAoACAAAAAAAAAAAQAgAAAAAAABAGAAAAAAAAEAiAAAAAAAAQCgAAAAAAABALgAAAAAAAEAyAAAAAAAAQDUAAAAAAABAOAAAAAAAAEA7AAAAAAAAQD4AAAAAAABAQIAAAAAAAEBCAAAAAAAAQEOAAAAAAABARQAAAAAAAEBGgAAAAAAAQEgAAAAAAABASYAAAAAAAEBLAAAAAAAAQEyAAAAAAABATgAAAAAAAEBPgAAAAAAAQFCAAAAAAABAUUAAAAAAAEBSAAAAAAAAQFLAAAAAAABAU4AAAAAAAEBUQAAAAAAAQFUAAAAAAABAVcAAAAAAAEBWgAAAAAAAQFdAAAAAAABAWAAAAAAAAEBYwAAAAAAAQFmAAAAAAABAWkAAAAAAAEBbAAAAAAAAQFvAAAAAAABAXIAAAAAAAEBdQAAAAAAAQF4AAAAAAABAXsAAAAAAAEBfgAAAAAAAQGAgAAAAAABAYIAAAAAAAEBg4AAAAAAAQGFAAAAAAABAYaAAAAAAAEBiAAAAAAAAQGJgAAAAAABAYsAAAAAAAEBjIAAAAAAAQGOAAAAAAABAY+AAAAAAAEBkQAAAAAAAQGSgAAAAAABAZQAAAAAAAEBlYAAAAAAAQGXAAAAAAABAZiAAAAAAAEBmgAAAAAAAQGbgAAAAAABAZ0AAAAAAAEBnoAAAAAAAQGgAAAAAAABAaGAAAAAAAEBowAAAAAAAQGkgAAAAAABAaYAAAAAAAEBp4AAAAAAAQGpAAAAAAABAaqAAAAAAAEBrAAAAAAAAQGtgAAAAAABAa8AAAAAAAEBsIAAAAAAAQGyAAAAAAABAbOAAAAAAAEBtQAAAAAAAQG2gAAAAAAA="
      """.trimIndent()
    }
  }
}
