/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.2.1/userguide/java_library_plugin.html
 */

plugins {
  // Apply the java-library plugin to add support for Java Library
  `java-library`
}

dependencies {
  compileOnlyApi(project(Projects.dependencies_sets_annotations))

  api(Libs.commons_io)
  api(Libs.commons_codec)
  api(Libs.guava)

  //Test stuff
  testImplementation(project(Projects.dependencies_sets_kotlin_test))
}
