package com.cedarsoft.common.kotlin.lang

import assertk.*
import assertk.assertions.*
import kotlin.test.Test

class ReflectionTest {
  @Test
  fun testReflection() {
    val myClass = MyClass("Martha", 155)

    assertThat(myClass.name).isEqualTo("Martha")
    assertThat(myClass.age).isEqualTo(155)

    assertThat(myClass::class.simpleName).isEqualTo("MyClass")
    val jsClass = myClass::class.js
    assertThat(jsClass.name).isEqualTo("MyClass")

    val props = props(myClass)
    assertThat(props.entries).hasSize(2)

    assertThat(props["name_1"]).isEqualTo("Martha") //strange name! Generated by Kotlin/JS
    assertThat(props["age_1"]).isEqualTo(155) //strange name! Generated by Kotlin/JS
  }
}

class MyClass(
  val name: String,
  age: Int,
) : MySuperClass(age)

open class MySuperClass(
  val age: Int,
)
